# Start with the base image for Python 3.8
FROM python:3.8

# Set the working directory for the app
WORKDIR /app

# Copy the requirements file into the image
COPY UI/requirements.txt .

# Install the Python dependencies
RUN pip install -r requirements.txt

# Copy the rest of the app code into the image
COPY UI/ /app/UI

# Expose the port that the app will run on
EXPOSE 7860

# Start the Gradio app
CMD ["python3", "./UI/index.py", "--share", "--port", "7860"]
